server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

spring:
  # DATABASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stockr-mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티에 맞춰 테이블 스키마 자동 변경
    show-sql: true # 실행되는 SQL 쿼리를 로그로 출력
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 예쁘게 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@stockr-mongodb:27017/${MONGO_DATABASE}?authSource=admin
    redis:
#      host: ${REDIS_HOST}
      host: localhost
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false
      lettuce:
        pool:
          enabled: true

  # KAFKA
  kafka:
    bootstrap-servers: stockr-kafka:29092
    consumer:
      group-id: stockr-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # WebSocket
  websocket:
    allowed-origins: "*"
    endpoint: /ws
    topic-prefix: /topic
    application-prefix: /app

  # config:
  #   activate:
  #     on-profile: test

logging:
  level:
    com.stockr: DEBUG
    org.springframework.web: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG # STOMP 메시지 로깅
    org.springframework.web.socket.messaging: TRACE # WebSocket 상세 로깅
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace # ? 로 표시되는 바인딩 파라미터 값까지 로그로 출력
    com.stockr.be: debug
    org.springframework.data.redis: debug
    io.lettuce.core: debug
